#!/bin/bash

# Create .env file
cat <<EOF > .env
ORG_NAME=$DEVOPS_ORGANISATION_NAME
PROJECT_NAME=$PROJECT_NAME
SOLUTION_NAME=$SOLUTION_NAME
RELEASE_VERSION=$RELEASE_VERSION
RELEASE_QUERY=$RELEASE_QUERY
PAT=$PAT
GPT_API_KEY=$GPT_API_KEY
SOFTWARE_SUMMARY=$SOFTWARE_SUMMARY
DESIRED_WORK_ITEM_TYPES=$DESIRED_WORK_ITEM_TYPES
OUTPUT_FOLDER=$OUTPUT_FOLDER
DEVOPS_API_VERSION=6.0
EOF

echo ".env file created successfully."