# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2024-06-08T14:56:48+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Avatar(BaseModel):
    href: str


class FieldLinks(BaseModel):
    avatar: Avatar


class CreatedBy(BaseModel):
    displayName: str
    url: str
    field_links: FieldLinks = Field(..., alias='_links')
    id: str
    uniqueName: str
    imageUrl: str
    descriptor: str


class FieldLinks1(BaseModel):
    avatar: Avatar


class ModifiedBy(BaseModel):
    displayName: str
    url: str
    field_links: FieldLinks1 = Field(..., alias='_links')
    id: str
    uniqueName: str
    imageUrl: str
    descriptor: str


class Comment(BaseModel):
    mentions: List
    workItemId: int
    id: int
    version: int
    text: str
    createdBy: CreatedBy
    createdDate: str
    modifiedBy: ModifiedBy
    modifiedDate: str
    format: str
    renderedText: str
    url: str


class Model(BaseModel):
    totalCount: int
    count: int
    comments: List[Comment]
