# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2024-06-09T07:10:30+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Avatar(BaseModel):
    href: str


class FieldLinks(BaseModel):
    avatar: Avatar


class SystemAssignedTo(BaseModel):
    displayName: str
    url: str
    field_links: FieldLinks = Field(..., alias='_links')
    id: str
    uniqueName: str
    imageUrl: str
    descriptor: str


class FieldLinks1(BaseModel):
    avatar: Avatar


class SystemCreatedBy(BaseModel):
    displayName: str
    url: str
    field_links: FieldLinks1 = Field(..., alias='_links')
    id: str
    uniqueName: str
    imageUrl: str
    descriptor: str


class FieldLinks2(BaseModel):
    avatar: Avatar


class SystemChangedBy(BaseModel):
    displayName: str
    url: str
    field_links: FieldLinks2 = Field(..., alias='_links')
    id: str
    uniqueName: str
    imageUrl: str
    descriptor: str


class FieldLinks3(BaseModel):
    avatar: Avatar


class SystemAuthorizedAs(BaseModel):
    displayName: str
    url: str
    field_links: FieldLinks3 = Field(..., alias='_links')
    id: str
    uniqueName: str
    imageUrl: str
    descriptor: str


class Fields(BaseModel):
    System_Id: int = Field(..., alias='System.Id')
    System_AreaId: int = Field(..., alias='System.AreaId')
    System_AreaPath: str = Field(..., alias='System.AreaPath')
    System_TeamProject: str = Field(..., alias='System.TeamProject')
    System_NodeName: str = Field(..., alias='System.NodeName')
    System_AreaLevel1: str = Field(..., alias='System.AreaLevel1')
    System_Rev: int = Field(..., alias='System.Rev')
    System_AuthorizedDate: str = Field(..., alias='System.AuthorizedDate')
    System_RevisedDate: str = Field(..., alias='System.RevisedDate')
    System_IterationId: int = Field(..., alias='System.IterationId')
    System_IterationPath: str = Field(..., alias='System.IterationPath')
    System_IterationLevel1: str = Field(..., alias='System.IterationLevel1')
    System_WorkItemType: str = Field(..., alias='System.WorkItemType')
    System_State: str = Field(..., alias='System.State')
    System_Reason: str = Field(..., alias='System.Reason')
    System_AssignedTo: SystemAssignedTo = Field(..., alias='System.AssignedTo')
    System_CreatedDate: str = Field(..., alias='System.CreatedDate')
    System_CreatedBy: SystemCreatedBy = Field(..., alias='System.CreatedBy')
    System_ChangedDate: str = Field(..., alias='System.ChangedDate')
    System_ChangedBy: SystemChangedBy = Field(..., alias='System.ChangedBy')
    System_AuthorizedAs: SystemAuthorizedAs = Field(..., alias='System.AuthorizedAs')
    System_PersonId: int = Field(..., alias='System.PersonId')
    System_Watermark: int = Field(..., alias='System.Watermark')
    System_CommentCount: int = Field(..., alias='System.CommentCount')
    System_Title: str = Field(..., alias='System.Title')
    System_BoardColumn: str = Field(..., alias='System.BoardColumn')
    System_BoardColumnDone: bool = Field(..., alias='System.BoardColumnDone')
    System_BoardLane: str = Field(..., alias='System.BoardLane')
    Microsoft_VSTS_Scheduling_StoryPoints: Optional[int] = Field(
        None, alias='Microsoft.VSTS.Scheduling.StoryPoints'
    )
    Microsoft_VSTS_Scheduling_RemainingWork: Optional[float] = Field(
        None, alias='Microsoft.VSTS.Scheduling.RemainingWork'
    )
    Microsoft_VSTS_Common_StateChangeDate: str = Field(
        ..., alias='Microsoft.VSTS.Common.StateChangeDate'
    )
    Microsoft_VSTS_Common_Priority: int = Field(
        ..., alias='Microsoft.VSTS.Common.Priority'
    )
    Microsoft_VSTS_Common_ValueArea: str = Field(
        ..., alias='Microsoft.VSTS.Common.ValueArea'
    )
    Microsoft_VSTS_Scheduling_Effort: Optional[float] = Field(
        None, alias='Microsoft.VSTS.Scheduling.Effort'
    )
    Microsoft_VSTS_Common_BacklogPriority: int = Field(
        ..., alias='Microsoft.VSTS.Common.BacklogPriority'
    )
    WEF_6C1948BB3D1C42339DB97D76FFA51204_System_ExtensionMarker: bool = Field(
        ..., alias='WEF_6C1948BB3D1C42339DB97D76FFA51204_System.ExtensionMarker'
    )
    WEF_6C1948BB3D1C42339DB97D76FFA51204_Kanban_Column: str = Field(
        ..., alias='WEF_6C1948BB3D1C42339DB97D76FFA51204_Kanban.Column'
    )
    WEF_6C1948BB3D1C42339DB97D76FFA51204_Kanban_Column_Done: bool = Field(
        ..., alias='WEF_6C1948BB3D1C42339DB97D76FFA51204_Kanban.Column.Done'
    )
    WEF_6C1948BB3D1C42339DB97D76FFA51204_Kanban_Lane: str = Field(
        ..., alias='WEF_6C1948BB3D1C42339DB97D76FFA51204_Kanban.Lane'
    )
    System_Description: Optional[str] = Field(None, alias='System.Description')
    System_Tags: str = Field(..., alias='System.Tags')
    System_Parent: int = Field(..., alias='System.Parent')
    System_IterationLevel2: Optional[str] = Field(None, alias='System.IterationLevel2')
    Microsoft_VSTS_Common_Severity: Optional[str] = Field(
        None, alias='Microsoft.VSTS.Common.Severity'
    )
    Microsoft_VSTS_CMMI_Blocked: Optional[str] = Field(
        None, alias='Microsoft.VSTS.CMMI.Blocked'
    )
    Microsoft_VSTS_TCM_ReproSteps: Optional[str] = Field(
        None, alias='Microsoft.VSTS.TCM.ReproSteps'
    )
    Microsoft_VSTS_Common_AcceptanceCriteria: Optional[str] = Field(
        None, alias='Microsoft.VSTS.Common.AcceptanceCriteria'
    )
    System_History: Optional[str] = Field(None, alias='System.History')
    Microsoft_VSTS_TCM_SystemInfo: Optional[str] = Field(
        None, alias='Microsoft.VSTS.TCM.SystemInfo'
    )


class Attributes(BaseModel):
    isLocked: Optional[bool] = None
    name: str
    authorizedDate: Optional[str] = None
    id: Optional[int] = None
    resourceCreatedDate: Optional[str] = None
    resourceModifiedDate: Optional[str] = None
    revisedDate: Optional[str] = None
    resourceSize: Optional[int] = None


class Relation(BaseModel):
    rel: str
    url: str
    attributes: Attributes


class Self(BaseModel):
    href: str


class WorkItemUpdates(BaseModel):
    href: str


class WorkItemRevisions(BaseModel):
    href: str


class WorkItemComments(BaseModel):
    href: str


class Html(BaseModel):
    href: str


class WorkItemType(BaseModel):
    href: str


class Fields1(BaseModel):
    href: str


class FieldLinks4(BaseModel):
    self: Self
    workItemUpdates: WorkItemUpdates
    workItemRevisions: WorkItemRevisions
    workItemComments: WorkItemComments
    html: Html
    workItemType: WorkItemType
    fields: Fields1


class CommentVersionRef(BaseModel):
    commentId: int
    version: int
    url: str


class ValueItem(BaseModel):
    id: int
    rev: int
    fields: Fields
    relations: List[Relation]
    field_links: FieldLinks4 = Field(..., alias='_links')
    url: str
    commentVersionRef: Optional[CommentVersionRef] = None


class Model(BaseModel):
    count: int
    value: List[ValueItem]
